package com.pms.billing.dto;

/*
 * =============================================================================
 * FILE: AvenantResponse -- the JSON the API sends back for one contract
 * amendment ("avenant").
 *
 * WHAT IT IS
 *   The read-side DTO of the amendment. A DTO (Data Transfer Object) is a small
 *   object whose only job is to carry data out of the application. This one is
 *   the flat, public picture of an Avenant row.
 *
 * WHERE IT SITS IN THE FLOW
 *   AvenantRepository gives Avenant entities to AvenantService
 *     -> AvenantService calls AvenantMapper.toResponse(...) / toResponseList(...)
 *        (MapStruct writes that mapper code at build time)
 *     -> BillingController returns it from
 *        GET  /api/projects/{projectId}/avenants   (the list)
 *        POST /api/projects/{projectId}/avenants   (the freshly created one)
 *     -> Jackson turns it into JSON
 *     -> Angular reads it as the interface Avenant in core/models/billing.model.ts
 *        and the billing screen prints the amendments table from it.
 *
 * WHY IT EXISTS (what would break if you deleted it)
 *   The controller would have to return the Avenant entity, and three things
 *   break at once:
 *   1. The entity holds a LAZY link to Project. Jackson serializes after the
 *      transaction is closed, so touching that link throws
 *      LazyInitializationException and the endpoint answers 500.
 *   2. If the link did load, every amendment row would drag the whole project
 *      (budget, client, funder, exchange rate...) into the JSON: a heavy
 *      payload full of fields the billing table has no reason to receive.
 *   3. The API shape would then follow the database. Renaming a column would
 *      silently break the Angular client. This record is the contract that
 *      protects the front end from the table.
 *
 * WHY IT IS A SEPARATE RECORD FROM AvenantRequest
 *   What goes in and what comes out are not the same thing: id, projectId and
 *   projectCode are produced by the server and must never be accepted from a
 *   caller. Two records make that mistake impossible.
 * =============================================================================
 */

import java.math.BigDecimal;
import java.time.LocalDate;

/*
 * A Java record: final and immutable, with the constructor and the accessors
 * generated by the compiler.
 *
 * WHY a record rather than a class with getters: a response object is built
 * once by the mapper and then only read. Immutability means no code between the
 * service and the JSON writer can change an amount after the permission check
 * has already passed.
 *
 * There are no validation annotations in this file, and that is normal: Bean
 * Validation guards what comes IN. This object only goes OUT, and its values
 * come from the database, which was validated on the way in.
 */
public record AvenantResponse(
        // Primary key of the amendment row. The Angular table uses it to build
        // the delete URL: DELETE /api/projects/{projectId}/avenants/{id}.
        Long id,
        /*
         * WHAT: projectId and projectCode are FLATTENED from the entity
         * association. AvenantMapper does it with
         * @Mapping(target = "projectId", source = "project.id") and
         * @Mapping(target = "projectCode", source = "project.code").
         * WHY: the caller needs to know which project the amendment belongs to,
         * but does not need the Project object itself. Reading two small values
         * keeps the payload flat, and because the mapper runs inside the service
         * transaction the LAZY proxy is resolved while the database session is
         * still open.
         * EXAMPLE without this flattening: exposing the Project object returns a
         * 500 (LazyInitializationException) or ships the full budget of the
         * project inside every single amendment row of the list.
         */
        Long projectId,
        // Human-readable project code ("PRJ-2026-004"). It sits next to
        // projectId so a screen or an export can show something a person
        // recognises without a second HTTP call to fetch the project.
        String projectCode,
        // The reference of the signed amendment, as it was sent in AvenantRequest.
        String numero,
        // The free-text purpose of the amendment. Can be null, because it is
        // optional on the way in, so the front end must handle an empty cell.
        String objet,
        /*
         * WHAT: the amount of the amendment, sign included. Positive means the
         * contract grew, negative means it was cut.
         * WHY BigDecimal: this is money. A double would start printing values
         * like 30000.000000000004 as soon as the browser adds rows together.
         * EXAMPLE of why the sign must survive to the screen: the amendments
         * table sums these values to explain the gap between the initial budget
         * and the revised budget. If a reduction arrived without its minus sign,
         * the explanation would not add up to the revised budget shown above it.
         */
        BigDecimal montant,
        // Impact on the sold workload in man-days (JH = jours-homme). Null when
        // the amendment changed money only; the Angular table prints a dash then.
        BigDecimal workloadDays,
        /*
         * The date the amendment was signed.
         * Jackson writes a LocalDate as the ISO string "2026-03-14", which is
         * what the Angular model declares as a string and what an
         * <input type="date"> expects. No time zone is involved, so the date
         * read in Tunis is exactly the date stored in the database.
         */
        LocalDate dateAvenant
) {}
