package com.pms.billing.dto;

/*
 * =============================================================================
 * FILE: FacturerRequest -- the very small JSON body sent to mark a billing
 * milestone as invoiced ("facturer" = to issue the invoice).
 *
 * WHAT IT IS
 *   A one-field DTO (Data Transfer Object: an object whose only job is to carry
 *   data into the application). It carries the date written on the invoice.
 *
 * WHERE IT SITS IN THE FLOW
 *   Angular BillingService.facturer() sends { dateFacture }
 *     -> PATCH /api/projects/{projectId}/jalons/{id}/facturer
 *     -> BillingController.facturer(..., @Valid @RequestBody FacturerRequest)
 *     -> JalonService.facturer(projectId, id, request), which requires the
 *        permission MANAGE_BILLING, refuses any milestone that is not in status
 *        PREVU, then sets statut = FACTURE and dateFacture = the date sent here.
 *   The updated milestone comes back as a JalonResponse.
 *
 * WHY IT EXISTS (what would break if you deleted it)
 *   Invoicing is a state change, not a full edit. JalonRequest cannot be reused
 *   here: it carries label, pourcentage and datePrevue, so accepting it would
 *   let the caller rewrite the milestone while pretending to only invoice it.
 *   And the date cannot be produced by the server either: the invoice is issued
 *   in the accounting tool, sometimes days before someone records it here, so
 *   the real invoice date has to travel from the client.
 *
 * WHY A RECORD FOR A SINGLE FIELD (instead of a query parameter)
 *   A JSON body can grow later (invoice number, currency) without breaking the
 *   clients that already call this endpoint, while adding a query parameter
 *   changes the URL itself. A body also keeps the date out of the URL, and
 *   therefore out of the server access logs.
 * =============================================================================
 */

import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;

/*
 * A Java record: immutable, with the constructor and the accessor dateFacture()
 * generated by the compiler. Jackson fills it from the JSON key "dateFacture".
 *
 * WHAT @NotNull does: it refuses a body where the date is missing or null. It
 * only runs because BillingController marks the parameter with @Valid, and a
 * failure is turned into HTTP 400 by GlobalExceptionHandler.handleValidation.
 * WHY it matters here more than it looks: JalonService.recalculerStatut uses
 * dateFacture as the proof that an invoice exists. When payments no longer
 * cover the amount it sends the milestone back to FACTURE if dateFacture is
 * set, and back to PREVU if it is null.
 * EXAMPLE without @NotNull: a milestone is invoiced with a null date, then a
 * payment that was typed by mistake is deleted; the milestone silently falls
 * back to PREVU although a real invoice was sent to the client, and it can then
 * be edited or deleted as if it had never been billed.
 */
public record FacturerRequest(@NotNull LocalDate dateFacture) {}
