package com.pms.billing.dto;

/*
 * =============================================================================
 * FILE: JalonResponse -- the JSON the API sends back for one billing milestone
 * ("jalon de facturation": one planned invoice, for example "30% on kick-off").
 *
 * WHAT IT IS
 *   The read-side DTO of the milestone (DTO = Data Transfer Object: a small
 *   object whose only job is to carry data out of the application). It is the
 *   flat, public picture of a JalonFacturation row, and it is richer than
 *   JalonRequest because it also carries what the server itself decided: the
 *   amount, the invoice date and the status.
 *
 * WHERE IT SITS IN THE FLOW
 *   JalonFacturationRepository gives JalonFacturation entities to JalonService
 *     -> JalonService calls JalonMapper.toResponse(...) / toResponseList(...)
 *        (MapStruct generates that mapper at build time)
 *     -> BillingController returns it from
 *        GET    /api/projects/{projectId}/jalons
 *        POST   /api/projects/{projectId}/jalons
 *        PUT    /api/projects/{projectId}/jalons/{id}
 *        PATCH  /api/projects/{projectId}/jalons/{id}/facturer
 *     -> Jackson turns it into JSON
 *     -> Angular reads it as the interface JalonFacturation in
 *        core/models/billing.model.ts; the billing screen decides from these
 *        values which buttons to show (invoice, edit, delete).
 *
 * WHY IT EXISTS (what would break if you deleted it)
 *   Returning the JalonFacturation entity would expose the LAZY link to
 *   Project: Jackson serializes once the transaction is closed, so reading that
 *   link throws LazyInitializationException (HTTP 500), and if it did load it
 *   would push the whole project row into every milestone of the list. It would
 *   also chain the API to the table: renaming a column would break the Angular
 *   client with no compiler warning anywhere.
 * =============================================================================
 */

import com.pms.billing.entity.JalonStatut;

import java.math.BigDecimal;
import java.time.LocalDate;

/*
 * A Java record: immutable, constructor and accessors generated by the compiler.
 *
 * WHY this response reuses the entity enum JalonStatut instead of copying it
 * into the dto package: JalonStatut is a closed list of three constant names
 * (PREVU, FACTURE, PAYE), not mutable state, so sharing it costs nothing and
 * stops the API and the database from drifting apart. A copied enum would have
 * to be kept in step by hand, and a new status added on one side only would be
 * silently mapped to the wrong value.
 *
 * No validation annotations here: Bean Validation guards what comes IN, and
 * this object only goes OUT.
 */
public record JalonResponse(
        // Primary key of the milestone row. The front end builds the invoice,
        // edit, delete and payment URLs from it.
        Long id,
        /*
         * WHAT: projectId and projectCode are FLATTENED from the entity
         * association by JalonMapper, with
         * @Mapping(target = "projectId", source = "project.id") and
         * @Mapping(target = "projectCode", source = "project.code").
         * WHY: the screen needs to know the project, not to receive it. The
         * mapper runs inside the service transaction, so the LAZY proxy is read
         * while the database session is still open.
         * EXAMPLE without the flattening: the endpoint answers 500
         * (LazyInitializationException), or a list of ten milestones repeats the
         * whole project (budget, client, funder) ten times.
         */
        Long projectId,
        // Human-readable project code, so an export or a shared screen can show
        // something a person recognises without a second call to the API.
        String projectCode,
        // The label of the milestone, as it was sent in JalonRequest.
        String label,
        // The share of the contract this milestone invoices, in percent.
        BigDecimal pourcentage,
        /*
         * WHAT: the money of this milestone. The client never sends it: the
         * server computes it in JalonService.computeMontant as
         * effectiveBudget x pourcentage / 100, rounded to 2 decimals with
         * HALF_UP, and stores it in the column jalons_facturation.montant.
         * WHY it is stored and not recomputed at read time: once a milestone is
         * invoiced or paid, its amount is an accounting fact and must stay
         * frozen even if the contract budget moves afterwards. While the
         * milestone is still PREVU it is kept in step by
         * JalonService.recomputePrevuMontants, which is called on every change
         * of the effective budget (marker H-4: amendment created, amendment
         * deleted, initial budget edited).
         * WHY it can be null: computeMontant returns null when the project has
         * no budget yet, so the front end must handle an empty amount.
         * EXAMPLE of what H-4 prevents: an amendment adds 100 000 to the
         * contract; without the recompute the PREVU milestones would still show
         * amounts based on the old budget, and the sum of the invoices to come
         * would no longer match the contract the client signed.
         */
        BigDecimal montant,
        // The date the milestone is expected to be invoiced (the cash forecast
        // is built on it). Null while the schedule is not known.
        LocalDate datePrevue,
        /*
         * The date written on the real invoice. It stays null until someone
         * calls PATCH .../facturer; it is therefore the simplest signal the
         * front end has that an invoice has really been issued, and
         * JalonService.recalculerStatut relies on the same signal when it has to
         * send a milestone back from PAYE to FACTURE or to PREVU.
         */
        LocalDate dateFacture,
        /*
         * WHAT: where the milestone stands: PREVU (planned), FACTURE (invoiced),
         * PAYE (fully paid). Jackson writes the constant name as a string, which
         * is exactly the union type 'PREVU' | 'FACTURE' | 'PAYE' declared in
         * billing.model.ts.
         * WHY the front end needs it: the whole behaviour of the billing screen
         * hangs on this value, because the server refuses to edit, delete or
         * re-invoice anything that is no longer PREVU, and refuses a payment on
         * a milestone that is still PREVU.
         * EXAMPLE without it: the screen would offer a Delete button on an
         * invoiced milestone; the user clicks, the server answers 422 with a
         * business rule error, and the application looks broken for a rule that
         * was in fact correct.
         */
        JalonStatut statut
) {}
