package com.pms.billing.dto;

/*
 * =============================================================================
 * FILE: PaiementRequest -- the JSON body sent to record money received from the
 * client against one billing milestone.
 *
 * WHAT IT IS
 *   A DTO (Data Transfer Object: a small object whose only job is to carry data
 *   into the application). It describes the only three fields a caller may send
 *   when the accounting team confirms that a payment has arrived.
 *
 * WHERE IT SITS IN THE FLOW
 *   Angular BillingService.createPaiement()
 *     -> POST /api/projects/{projectId}/jalons/{jalonId}/paiements
 *     -> BillingController.createPaiement(..., @Valid @RequestBody PaiementRequest)
 *     -> PaiementService.create(projectId, jalonId, request), which requires the
 *        permission MANAGE_BILLING, checks that the milestone really belongs to
 *        that project, refuses a payment on a milestone still in status PREVU
 *        (money cannot arrive before an invoice was issued), saves the Paiement
 *        row, then calls JalonService.recalculerStatut: when the payments add up
 *        to the amount of the milestone, the milestone becomes PAYE.
 *   What comes back is a PaiementResponse.
 *
 * WHY IT EXISTS (what would break if you deleted it)
 *   Without it the controller would accept the Paiement entity, and a caller
 *   could send "jalon": {...} or "deleted": true and attach a payment to a
 *   milestone of another project, or resurrect a deleted row. Here the
 *   milestone is chosen by the URL only, and the URL is guarded by
 *   ProjectScopeInterceptor (ADR-021), which checks the permission AND that the
 *   user is inside the scope of that project.
 *
 * WHAT IS DELIBERATELY ABSENT
 *   There is no jalonId and no projectId in the body: both come from the URL,
 *   so the row that is checked is always the row that is written. There is no
 *   status either: the status of the milestone is decided by the server from
 *   the sum of the payments, never sent by the client.
 * =============================================================================
 */

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.time.LocalDate;

/*
 * A Java record: final and immutable, constructor and accessors generated by
 * the compiler, built by Jackson from the JSON keys of the same names.
 *
 * WHY immutable: the amount that the rules below accept must be the very same
 * amount that is saved and then added up by recalculerStatut. A mutable object
 * would leave room for a value to change between the check and the write.
 *
 * The rules only run because BillingController marks the parameter with @Valid;
 * a failure becomes HTTP 400 naming the field, through
 * GlobalExceptionHandler.handleValidation.
 */
public record PaiementRequest(
        /*
         * WHAT: the money actually received. @NotNull requires the value,
         * @Positive requires it to be strictly greater than zero, so 0 and
         * negative amounts are both refused.
         * WHY a partial payment is still allowed: the amount does not have to
         * equal the milestone, because clients often pay in several transfers;
         * JalonService.recalculerStatut compares the SUM of the payments with
         * the amount of the milestone and only then switches it to PAYE.
         * WHY BigDecimal and not double: money must be exact. With a double,
         * adding several payments drifts (0.1 + 0.2 gives 0.30000000000000004)
         * and a milestone could stay one cent short of PAYE forever.
         * WHY @Positive even though the database already has
         * CHECK (montant_recu > 0): the database answers with a vague 409
         * "constraint violated", while this rule answers 400 and names the
         * field, so the form can show the error on the right input.
         * EXAMPLE without @Positive: someone records a refund as -500; the sum
         * of the payments falls below the amount of the milestone and
         * recalculerStatut drags a milestone that was really paid back out of
         * PAYE, so the cash-in figures of the project become false.
         */
        @NotNull @Positive BigDecimal montantRecu,
        /*
         * WHAT: @NotNull forces the date the money arrived (value date of the
         * transfer), not the day someone typed the row.
         * WHY: it is the date on which the cash-in of the project is counted,
         * and the date an auditor matches against the bank statement.
         * WHY LocalDate: a bank value date is a day; an hour would add a time
         * zone problem for nothing.
         * EXAMPLE without it: payments cannot be placed on a month, so "how much
         * did we actually cash in during this quarter?" has no answer, and a
         * payment recorded late looks like it arrived late.
         */
        @NotNull LocalDate datePaiement,
        /*
         * The bank or accounting reference of the transfer ("VIR-2026-0142").
         * Optional on purpose: the payment is a fact even when the reference is
         * still missing, so the team is not blocked. When it is filled it is
         * what lets someone match this row with a line on the bank statement.
         * Column: VARCHAR(255), nullable.
         */
        String reference
) {}
