package com.pms.project.dto;

import com.pms.project.entity.BusinessModel;
import com.pms.project.entity.EngagementType;
import com.pms.project.entity.ProjectStatus;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/*
 * FILE: ProjectResponse.java
 *
 * WHAT THIS FILE IS
 * The shape of one project as the browser receives it. It is a DTO (Data Transfer Object): an
 * object whose only job is to carry data over the network. It carries the stored columns, the
 * two people in charge already flattened to id plus name, and three figures the server computes
 * (duration, budget in dinars, risk provision). It also holds withoutFinancials(), the one piece
 * of logic in this file, which returns a copy with every money value removed.
 *
 * WHERE IT SITS IN THE FLOW
 *   ProjectService (findAll, findById, create, update, archive, changeStatus, ...)
 *     -> ProjectMapper.toResponse(project), generated by MapStruct, fills this record from the
 *        Project entity
 *     -> ProjectService.toResponse(...) then calls withoutFinancials() when the caller does not
 *        hold VIEW_KPI
 *     -> ProjectController returns it, and Spring writes it as JSON for the Angular screens
 *        (project list, project detail, dashboards).
 * The way in is the other record of this package, ProjectRequest.
 *
 * WHY IT EXISTS
 * Three things would break without it.
 * 1. The Project entity has lazy links to two User rows. Serialising the entity would either
 *    fail on a closed session or drag whole user records, password hash included, into the JSON.
 * 2. The screen needs directorName and chefProjetName. An entity cannot offer a flat name
 *    without pulling the full user object along with it.
 * 3. Nothing could be hidden. withoutFinancials() only exists because the response is a separate
 *    object from the entity: you cannot null a column on an entity without deleting real data.
 *
 * THE FINANCIAL WALL (BR-050)
 * Removing the VIEW_KPI permission from developers closed the KPI endpoints, but not this
 * payload: GET /api/projects/{id} only asks for VIEW_PROJECT, so a developer assigned to a
 * project still received the budget, the provision and the margin inside the project itself.
 * withoutFinancials() closes that hole in the payload. Note how the fix is written: the code
 * asks whether the caller holds the VIEW_KPI permission, never whether he "is a developer"
 * (ADR-001, dynamic permission-based authorization). Give VIEW_KPI to another role tomorrow and
 * the behaviour follows, with no code change.
 */

/**
 * One project, as read by the client.
 *
 * Why a record: it is immutable, so the redaction below cannot be undone further down the chain.
 * withoutFinancials() does not blank the current object, it builds a new one; the full version
 * simply never leaves ProjectService for a caller without VIEW_KPI.
 *
 * Why it carries directorId and directorName rather than a nested user object: the screen needs
 * only those two values, and sending a whole user record with every project would expose data
 * the project page has no reason to show.
 */
public record ProjectResponse(
        Long id,
        // Business key of the project, always upper-case, for example "PRJ-2024-07".
        String code,
        String name,
        String description,
        // Lifecycle state: DRAFT, ACTIVE, ON_HOLD, COMPLETED or CANCELLED. The allowed moves
        // between them live in the ProjectStatus enum itself, not here.
        ProjectStatus status,
        LocalDate startDate,
        LocalDate endDate,
        // The three budget figures, in the project currency.
        // initialBudget is what the contract was signed for; revisedBudget is what the avenants
        // (contract amendments) made of it, and is null while no avenant exists; effectiveBudget
        // is the one to use in any calculation. The mapper fills it by calling
        // Project.getEffectiveBudget(), which returns revisedBudget when there is one and
        // initialBudget otherwise.
        // Why all three travel together: a reader must be able to see that a budget of 650 000
        // became 700 000, and why. Sending only the effective figure would hide the amendment.
        BigDecimal initialBudget,
        BigDecimal revisedBudget,
        BigDecimal effectiveBudget,
        // The director and the project manager, flattened to an id plus a display name.
        // Both are null when nobody is assigned yet, which is normal for a project in DRAFT.
        Long directorId,
        String directorName,
        Long chefProjetId,
        String chefProjetName,

        // -- Identification sheet (Excel model) -------------------
        // Reference of the signed contract.
        String contractId,
        // The client who signs, and the funder who pays. They are often different: a ministry
        // signs while a development bank funds.
        String client,
        String funder,
        // SEUL (the company alone) or GROUPEMENT (a consortium with partners).
        BusinessModel businessModel,
        // FORFAIT (fixed price, the company carries the risk of the extra days) or REGIE (time
        // and materials, the client pays the days actually spent).
        EngagementType engagementType,
        // Contract currency (TND, EUR, FCFA...) and how many dinars one of its units is worth.
        // They are sent even to a reader without financial rights, because they are labels, not
        // amounts, and because every converted figure below is meaningless without them.
        String currency,
        BigDecimal exchangeRateToTnd,
        // Share of the budget that goes to bought licences and to subcontractors.
        BigDecimal licenseSubcontractBudget,
        // Workload sold to the client, and workload kept for the warranty period, both in JH
        // (one person working one day).
        // These are quantities, not money, so withoutFinancials() keeps them: a developer may
        // legitimately know how many days were sold on his project, but not for how much.
        BigDecimal soldWorkloadDays,
        BigDecimal warrantyWorkloadDays,
        // Money set aside for the late-delivery penalties written in the contract.
        BigDecimal penaltyProvision,
        // Net margin sold, as a fraction: 0.4412 means 44.12 %. This is the commercial baseline
        // typed on the identification sheet; when the project has Devis Interne lines, the
        // margin computed from them takes priority.
        BigDecimal margeNetteVendue,

        // True when the project has been closed and moved out of the active lists. It is a flag,
        // not a status, so a project stays COMPLETED and archived at the same time.
        // It is the primitive "boolean" and not the wrapper "Boolean", unlike every other field
        // of this record. A primitive cannot hold null, so the JSON always carries true or
        // false and the Angular list never has to handle a missing value before filtering the
        // archived rows out.
        boolean archived,

        // -- Audit -----------------------------------------------
        // When the project row was created, kept by the shared BaseEntity. Useful to the jury
        // question "how do you know who entered this and when": every entity inherits the audit
        // columns rather than repeating them.
        LocalDateTime createdAt,

        // -- Computed fields (not stored) ------------------------
        // Contract length in days, both ends included, exactly like the Excel sheet: a project
        // running from the 1st to the 31st of a month counts 31 days, not 30. It is null while
        // one of the two dates is missing.
        // Why computed and not stored: a stored duration would silently become false the first
        // time somebody corrects an end date.
        Long durationDays,
        // Effective budget converted into dinars: effectiveBudget x exchangeRateToTnd.
        // Like durationDays it is null, not 0, when there is no budget at all, and the getter
        // falls back to a rate of 1 when the project has none. Why null matters here: a
        // budget of 0 TND on screen reads as "this project has no money", while an empty box
        // reads as "not filled in yet" - which is the truth for a project still in DRAFT.
        BigDecimal budgetTnd,
        // PPR, "Provision Pour Risques" (provision for risks) = budgetTnd x 5 %, the rate fixed
        // by the company identification sheet.
        // Why derived here and not written into a column: it depends on the budget and on the
        // exchange rate. Stored, it would keep the old figure after an avenant raises the budget,
        // and the project would look covered against a risk it no longer is.
        BigDecimal pprTnd
) {

    /**
     * Returns a copy of this project with every financial value removed (amounts and margin).
     *
     * BR-050: users without the VIEW_KPI permission (a developer, for example) are walled off
     * from financial data. The workload figures in JH (soldWorkloadDays, warrantyWorkloadDays)
     * are not financial and stay visible.
     *
     * What it gives back: a new ProjectResponse with the same identity, dates, people and
     * workload, and with null in the place of every amount. It never changes the current object.
     *
     * Why a copy instead of hiding the fields another way: a record is immutable, so there is
     * nothing to blank in place; and a JSON-level filter would hide the numbers only in the HTTP
     * answer, leaving them inside any object the server passes around or logs. Building a
     * redacted copy makes the redaction part of the data itself.
     *
     * Why null and not 0: zero is a value a reader would believe. A project displayed with a
     * budget of 0 looks like a project with no money, while null lets the screen show nothing at
     * all, which is the truth ("you may not see this").
     *
     * Note for the reader: the constructor below is positional, so the order of the arguments
     * must follow the order of the components declared above, one for one.
     */
    public ProjectResponse withoutFinancials() {
        return new ProjectResponse(
                id, code, name, description, status, startDate, endDate,
                // the three budgets go away: this is the data BR-050 is about
                null, null, null,                       // initialBudget, revisedBudget, effectiveBudget
                directorId, directorName, chefProjetId, chefProjetName,
                // identity of the contract stays: it is who and what, never how much.
                // currency and exchangeRateToTnd stay too, because they are labels, not amounts
                contractId, client, funder, businessModel, engagementType, currency, exchangeRateToTnd,
                null,                                   // licenseSubcontractBudget
                // kept on purpose: days sold and days of warranty are workload, not money
                soldWorkloadDays, warrantyWorkloadDays,
                null,                                   // penaltyProvision
                null,                                   // margeNetteVendue
                // durationDays is kept: a calendar length tells nothing about money
                archived, createdAt, durationDays,
                // both derived from the budget, so they would leak it back: budgetTnd is the
                // budget itself converted, and pprTnd is 5 % of it, which anyone can multiply
                // by 20 to recover the budget
                null, null                              // budgetTnd, pprTnd
        );
    }
}
