@startuml class_security
title Classes — Sécurité et Contrôle d'Accès

left to right direction

skinparam shadowing false
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #2C5F8A
skinparam classHeaderBackgroundColor #D6E4F0
skinparam defaultFontName Helvetica
skinparam defaultFontSize 12
skinparam ArrowColor #444444
skinparam ArrowThickness 1.5
skinparam noteBorderColor #999999
skinparam noteBackgroundColor #FFFDE7
hide circle

class Utilisateur {
  - email : String
  - motDePasse : String
  - actif : boolean
  - premierAcces : boolean
  --
  + authentifier() : JetonAcces
  + changerMotDePasse() : void
  + revoquerSession() : void
}

class Role {
  - nom : String
  --
  + verifierPermission(code : String) : boolean
}

class Permission {
  - code : String
  - module : String
}

Utilisateur "1" --> "1" Role       : possède >
Role        "1" --> "*" Permission  : accorde >

note bottom of Role
  Rôles prédéfinis :
  ADMIN · DIRECTEUR
  CHEF_PROJET · DEVELOPPEUR
end note

note right of Permission
  Exemple : code = ASSIGN_DEVELOPER
  module = PROJET
  Le mapping est configurable
  en base de données (RBAC dynamique).
end note

@enduml
